language: haskell

script:
  - cabal install --only-dependencies && cabal configure && cabal build && cabal bench

before_install:
  - cabal update

install:
  - cabal install --only-dependencies
  
notifications:
  email:
      - alpmestan@gmail.com
  irc: "irc.freenode.org#haskell-math"
